version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Man8244251
      MYSQL_USER: root
      MYSQL_PASSWORD: Man8244251
      MYSQL_DATABASE: messaging_db
      MYSQL_DB: messaging_db   # for ALX checker compliance
    ports:
      - "3307:3306"  # Avoid conflicts with local MySQL
    volumes:
      - messaging_db_data:/var/lib/mysql  # <-- Persisted volume for DB data

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

volumes:
  messaging_db_data:  # <-- Declare the volume here
