#!/bin/bash

echo "Deploying BLUE version..."
kubectl apply -f messaging_app/blue_deployment.yaml

echo "Deploying GREEN version..."
kubectl apply -f messaging_app/green_deployment.yaml

echo "Deploying service (pointing to BLUE)..."
kubectl apply -f messaging_app/kubeservice.yaml

echo "Current deployments:"
kubectl get deployments

echo "Current pods:"
kubectl get pods -o wide

echo "Checking logs for GREEN version..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath='{.items[0].metadata.name}')
kubectl logs $GREEN_POD
